nombre : Compilación WsaPatch.dll

en :
  empujar :
    ramas : [ "principal" ]
  pull_request :
    ramas : [ "principal" ]

env :
  # Ruta al archivo de solución relativa a la raíz del proyecto.
  RUTA_ARCHIVO_SOLUCIÓN : .
  BUILD_CONFIGURATION : Lanzamiento

permisos :
  contenido : leer

trabajos :
  construir :
    se ejecuta : windows-latest

    pasos :
      - nombre : Caja
        usos : acciones/checkout@v3

      - nombre : Configurar
        ejecutar : |
          cmake -G "Visual Studio 17 2022" -A x64 -B compilación
      - nombre : versión de compilación
        ejecutar : cmake --build build --config Release --verbose

      - nombre : Cargar WsaPatch.dll
        usos : acciones/subir-artefacto@v3
        con :
          nombre : WsaPatch-compilación
          ruta : .\construir
